set export := true

# set default versions
alpine_version := "3.21"
default_vey_version := "1.13.9"
build_target := "${CARGO_BUILD_TARGET:-aarch64-apple-darwin}"

# run `just` in the CLI to see the list of shortcuts
_default:
	just --list

# verify the existence of critical tools
verify:
	@rustup --version
	@cargo --version
	@docker --version
	@git --version
	@jq --version

# install all required packages using brew
setup: verify
	brew install filosottile/musl-cross/musl-cross
	brew install pkgconf capnp c-ares openssl

# build binary and docker image using a given version
build version=default_vey_version: verify
	@echo ""
	@echo "Using VEY version {{version}}"
	@echo "Verifying existence of critical tools"
	@echo ""

	@echo "Clone from GIT {{version}}..."
	-@rm -rf ./vey
	-@rm -rf ./vey-proxy
	@git config --global advice.detachedHead false
	@git clone --depth 1 --branch vey-proxy-v{{version}} --quiet https://github.com/VEY-OSS/vey.git
	@echo ""

	@echo "Build with Rust for {{build_target}}..."
	@rustup target add {{build_target}}
	@cargo build \
		--target {{build_target}} \
		--profile release-lto \
		--no-default-features \
		--features quic,c-ares,rustls-ring \
		-p vey-proxy \
		--manifest-path vey/Cargo.toml
	@mv ./vey/target/{{build_target}}/release-lto/vey-proxy ./vey-proxy
	-@rm -rf vey
	@./vey-proxy --version

	@docker build \
		-t vey-proxy:ipv4-only \
		--platform "linux/amd64" \
		--build-arg ALPINE_VERSION={{alpine_version}} \
		--build-arg PROXY_CONFIG_FILE=vey-proxy.ipv4-only.yml .
	-@echo "Image size IPv4: $(docker images vey-proxy:ipv4-only --format json | jq -r .Size)"

	@docker build \
		-t vey-proxy:ipv6-first \
		--platform "linux/amd64" \
		--build-arg ALPINE_VERSION={{alpine_version}} \
		--build-arg PROXY_CONFIG_FILE=vey-proxy.ipv6-first.yml .
	-@echo "Image size IPv6: $(docker images vey-proxy:ipv6-first --format json | jq -r .Size)"

# list rustup targets
targets:
	@rustup target list

# remove files and docker images
cleanup:
	-rm -rf vey
	-docker rmi alpine
	-docker rmi vey-proxy
	-docker image prune -f
